# Generated by Django 4.2.4 on 2023-10-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(default='', max_length=300),
        ),
    ]
