# Generated by Django 4.2.4 on 2023-10-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.TextField(),
        ),
    ]
